### ISSUE TITLE
Clear doesn't notify collection changed

### ISSUE THREAD

**Issue by codingdna2** [YounesCheikh/ObservableConcurrentQueue#7]
Hello, I've noticed that calling the Clear method doesn't raise the CollectionChanged.
Is the library still mantained?
If needed I can submit a PR.
Thanks in advance,
D.

**Comment by YounesCheikh** [comment]
Hi @codingdna2 

The method ` Clear() ` has been introduced in [ .NET Core](https://learn.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentqueue-1.clear?view=netcore-3.1#system-collections-concurrent-concurrentqueue-1-clear)  while this package is still supporting .NET Framework versions.  

Don't hesitate to build your own version supporting only .NET Core then implement the notifications on Clear calls 😃 

Best regards, 
Younes

**Comment by codingdna2** [comment]
Hi! Thanks for your response!

What about something like:

```cs
#if !NETFRAMEWORK && (NETSTANDARD2_1_OR_GREATER || NETCOREAPP2_0_OR_GREATER)
        public new void Clear()
        {
            base.Clear();

            // Raise event added event
            this.OnContentChanged(
                new NotifyConcurrentQueueChangedEventArgs<T>(NotifyConcurrentQueueChangedAction.Empty));
        }
#endif
```
I've committed on my [fork](https://github.com/codingdna2/ObservableConcurrentQueue), you if like to integrate it, I'll push a PR.
Best regards,
D.
